In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [ ]:
# importing the dataset

pk = pd.read_csv('/content/Parkinsson disease.csv')
pk

               name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...   spread2        D2       PPE
0    phon_R01_S01_1      119.992       157.302  ...  0.266482  2.301442  0.284654
1    phon_R01_S01_2      122.400       148.650  ...  0.335590  2.486855  0.368674
2    phon_R01_S01_3      116.682       131.111  ...  0.311173  2.342259  0.332634
3    phon_R01_S01_4      116.676       137.871  ...  0.334147  2.405554  0.368975
4    phon_R01_S01_5      116.014       141.781  ...  0.234513  2.332180  0.410335
..              ...          ...           ...  ...       ...       ...       ...
190  phon_R01_S50_2      174.188       230.978  ...  0.121952  2.657476  0.133050
191  phon_R01_S50_3      209.516       253.017  ...  0.129303  2.784312  0.168895
192  phon_R01_S50_4      174.688       240.005  ...  0.158453  2.679772  0.131728
193  phon_R01_S50_5      198.764       396.961  ...  0.207454  2.138608  0.123306
194  phon_R01_S50_6      214.289       260.277  ...  0.190667  2.555477  0.148569

[195 rows x 24 columns]

In [ ]:
pk.head()

             name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...   spread2        D2       PPE
0  phon_R01_S01_1      119.992       157.302  ...  0.266482  2.301442  0.284654
1  phon_R01_S01_2      122.400       148.650  ...  0.335590  2.486855  0.368674
2  phon_R01_S01_3      116.682       131.111  ...  0.311173  2.342259  0.332634
3  phon_R01_S01_4      116.676       137.871  ...  0.334147  2.405554  0.368975
4  phon_R01_S01_5      116.014       141.781  ...  0.234513  2.332180  0.410335

[5 rows x 24 columns]

In [ ]:
pk.describe()

       MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...          D2         PPE
count   195.000000    195.000000  ...  195.000000  195.000000
mean    154.228641    197.104918  ...    2.381826    0.206552
std      41.390065     91.491548  ...    0.382799    0.090119
min      88.333000    102.145000  ...    1.423287    0.044539
25%     117.572000    134.862500  ...    2.099125    0.137451
50%     148.790000    175.829000  ...    2.361532    0.194052
75%     182.769000    224.205500  ...    2.636456    0.252980
max     260.105000    592.030000  ...    3.671155    0.527367

[8 rows x 23 columns]

In [ ]:
pk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              195 non-null    object
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 17  status            195 non-null    int64
 18  RPDE              195 non-null    float64
 19  DFA               195 non-null    float64
 20  spread1           195 non-null    float64
 21  spread2           195 non-null    float64
 22  D2                195 non-null    float64
 23  PPE               195 non-null    float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.7+ KB

In [ ]:
pk.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [ ]:
pk["status"].value_counts()

status
1    147
0     48
Name: count, dtype: int64

1  -> who have the disease
0  -> who does not have the disease

In [ ]:
x = pk.drop(columns = ['name','status'], axis=1)
y = pk['status']

In [ ]:
print(x)

     MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  ...   spread2        D2       PPE
0        119.992       157.302        74.997  ...  0.266482  2.301442  0.284654
1        122.400       148.650       113.819  ...  0.335590  2.486855  0.368674
2        116.682       131.111       111.555  ...  0.311173  2.342259  0.332634
3        116.676       137.871       111.366  ...  0.334147  2.405554  0.368975
4        116.014       141.781       110.655  ...  0.234513  2.332180  0.410335
..           ...           ...           ...  ...       ...       ...       ...
190      174.188       230.978        94.261  ...  0.121952  2.657476  0.133050
191      209.516       253.017        89.488  ...  0.129303  2.784312  0.168895
192      174.688       240.005        74.287  ...  0.158453  2.679772  0.131728
193      198.764       396.961        74.904  ...  0.207454  2.138608  0.123306
194      214.289       260.277        77.973  ...  0.190667  2.555477  0.148569

[195 rows x 22 columns]

In [ ]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
190    0
191    0
192    0
193    0
194    0
Name: status, Length: 195, dtype: int64

spliting the data for the trainning and testing

In [ ]:
train_x , test_x,train_y,test_y = train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
print(train_x)

     MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  ...   spread2        D2       PPE
123      182.018       197.173        79.187  ...  0.142466  2.174306  0.215558
160      114.238       124.393        77.022  ...  0.259229  2.151121  0.244948
94       157.821       172.975        68.401  ...  0.188056  2.143851  0.160812
57       117.274       129.916       110.402  ...  0.290024  2.021591  0.314464
41       184.055       196.537       166.977  ...  0.063412  2.361532  0.115730
..           ...           ...           ...  ...       ...       ...       ...
43       241.404       248.834       232.483  ...  0.158266  2.256699  0.117399
22       167.930       193.221        79.068  ...  0.262384  2.916777  0.285695
72       120.080       139.710       111.208  ...  0.329066  2.205024  0.188180
15       142.167       217.455        83.159  ...  0.210185  2.205546  0.234589
168      197.569       217.627        90.794  ...  0.164529  2.882450  0.202879

[156 rows x 22 columns]

In [ ]:
print(test_x)

     MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  ...   spread2        D2       PPE
10        88.333       112.240        84.072  ...  0.391002  2.407313  0.249740
79       100.770       115.697        85.545  ...  0.265699  2.398422  0.277948
164      102.273       142.830        85.902  ...  0.396746  2.560422  0.367233
142      198.458       219.290       148.691  ...  0.310746  2.465528  0.209863
186      116.556       592.030        86.228  ...  0.153310  2.161936  0.120605
133      118.747       123.723       109.836  ...  0.178713  2.034827  0.141422
35       201.464       210.565       195.708  ...  0.170183  2.447064  0.057610
137      113.166       130.270       100.673  ...  0.304107  2.672362  0.274387
25       104.400       206.002        77.968  ...  0.236853  2.846369  0.219514
2        116.682       131.111       111.555  ...  0.311173  2.342259  0.332634
12       136.926       159.866       131.276  ...  0.152813  2.041277  0.138512
128      119.031       127.533       109.216  ...  0.152941  2.328513  0.112856
144      202.544       241.350       164.168  ...  0.220617  2.576563  0.159777
3        116.676       137.871       111.366  ...  0.334147  2.405554  0.368975
48       122.188       128.611       115.765  ...  0.266392  2.079922  0.133867
29       162.568       198.346        77.630  ...  0.209866  1.957961  0.135242
14       152.845       163.305        75.836  ...  0.203653  2.125618  0.170100
119      217.116       233.481        93.978  ...  0.389295  2.925862  0.220657
6        120.267       137.244       114.820  ...  0.257682  1.854785  0.211756
23       173.917       192.735        86.180  ...  0.210279  2.547508  0.253556
108      151.989       157.339       132.857  ...  0.160686  2.296873  0.115130
143      202.805       231.508        86.232  ...  0.213353  2.470746  0.189032
129      120.078       126.632       105.667  ...  0.195976  2.108873  0.183572
174      117.004       144.466        99.923  ...  0.229298  1.872946  0.163118
45       242.852       255.034       227.911  ...  0.102083  2.365800  0.102706
120      128.940       479.697        88.251  ...  0.279933  2.686240  0.152428
173      113.715       116.443        96.913  ...  0.192150  1.852542  0.179677
125      145.174       198.109        80.637  ...  0.127950  1.765957  0.222716
9         95.056       120.103        91.226  ...  0.325996  2.432792  0.271362
163      112.150       131.669        97.527  ...  0.184896  1.871871  0.212386
54       108.807       134.656       102.874  ...  0.205558  1.986899  0.316700
13       139.173       179.139        76.556  ...  0.254989  2.519422  0.199889
109      193.030       208.900        80.297  ...  0.278679  2.608749  0.185668
194      214.289       260.277        77.973  ...  0.190667  2.555477  0.148569
78        95.385       102.145        90.264  ...  0.249494  2.017753  0.260015
114      206.327       226.355        92.020  ...  0.181701  2.938114  0.115515
44       243.439       250.912       232.435  ...  0.091608  2.330716  0.091470
82       100.960       110.019        95.628  ...  0.146948  2.428306  0.264666
158      126.144       154.284        97.543  ...  0.280091  2.892300  0.249703

[39 rows x 22 columns]

In [ ]:
print(x.shape,train_x.shape,test_x.shape)

(195, 22) (156, 22) (39, 22)

In [ ]:
# data standartization

std =  StandardScaler()

In [ ]:
std.fit(train_x)

StandardScaler()

In [ ]:
train_x = std.transform(train_x)

test_x = std.transform(test_x)

In [ ]:
#importing the svm model

model = svm.SVC(kernel='linear')

In [ ]:
model.fit(train_x,train_y)

SVC(kernel='linear')

In [ ]:
# to find the  accuracy of the trainning data

train_pred = model.predict(train_x)
acc= accuracy_score(train_pred,train_y)
print(acc)

0.8846153846153846

In [ ]:
# accuracy score on training data
X_test_prediction = model.predict(test_x)
test_data_accuracy = accuracy_score(test_y, X_test_prediction)
print('Accuracy score of test data : ', test_data_accuracy)

Accuracy score of test data :  0.8717948717948718